version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: paulor-barber-postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

volumes:
  .postgres-data:
